services:
  - type: web
    name: survey-polling-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn survey_and_poll.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: survey_polling_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false

databases:
  - name: survey_polling_db
    plan: free